name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ hashFiles('package.json') }}
      - uses: Project-Env/project-env-github-action@v1.4.0
      - run: npm install
      - run: npm run package